# Generated by Django 3.2.9 on 2021-12-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.TextField(verbose_name='2021-12-06T11:07:50.428560'),
        ),
    ]
