# Generated by Django 3.2.9 on 2021-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.CharField(default='2021-12-06T11:09:52.807344', max_length=50),
        ),
    ]
