# Generated by Django 3.2.9 on 2021-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211208_1040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviesInList',
            new_name='MovieInList',
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.CharField(default='2021-12-08T11:19:02.436298', max_length=50),
        ),
    ]
