# Generated by Django 3.2.9 on 2021-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211208_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.CharField(default='2021-12-08T11:21:38.296859', max_length=50),
        ),
    ]
