# Generated by Django 3.2.9 on 2021-12-10 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_alter_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.CharField(default='2021-12-10T09:39:14.276572', max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('date', models.CharField(default='2021-12-10T09:39:14.277009', max_length=50)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
