# Generated by Django 3.2.9 on 2021-12-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211210_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(default='2021-12-11T22:40:39.675667', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.CharField(default='2021-12-11T22:40:39.675245', max_length=50),
        ),
    ]
