# Generated by Django 3.2.9 on 2021-12-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20211211_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(default='2021-12-12T11:39:12.107701', max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.CharField(default='2021-12-12T11:39:12.107388', max_length=50),
        ),
    ]
